blank_issues_enabled: false
contact_links:
  - name: Readme
    url: https://github.com/catbee-technologies/cron-parser#readme
    about: Check the README for more information about the project.
  - name: Documentation
    url: https://catbee.in/docs/@catbee/utils/intro
    about: Find in-depth information about using cron-parser in the docs.
  - name: Discussions
    url: https://github.com/catbee-technologies/cron-parser/discussions
    about: Ask questions or start a discussion here.
  - name: Security Policy
    url: https://github.com/catbee-technologies/cron-parser/security/policy
    about: Report security vulnerabilities responsibly here.
